MyCards.jsxというコンポーネントを新たに作成し、2回目以降のSETボタン押下時はそこに吐き出されるようにしました
TsukasaKashima/OFC-Practice pull request #74
Opened 2020-09-21 09:56 UTC by TsukasaKashima

掲題の通りです。

カードをセットもしくはリセットする際の条件分岐も細かく設定し、矛盾ない枚数でカードが吐き出されるようにしました。
（各パターン、総当たりでテストと検証済みです）

いったんリファクタリング等の作業は差し置きまして、まずは指摘された機能を実装してデプロイするまでを第一の目標としたいので、次のissueに取組まさせていただきます。（ポートフォリオにはもう大きい時間をかけたくないというところがあるので。。）

2020-09-21 13:59 UTC, azusa-ttt requested changes

2020-09-21 13:59 UTC, azusa-ttt commented on src/component/Game/index.jsx
> +      //219行目の書き方っぽい
細かい内容の面では特に指摘ありませんが、こちらのコメントはちょっと意図がよめなかったです。
(多分、1年後くらいにこのソースを読むと、なんのためのコメントだったかご自身でもわからなくなってしまう気がします)

必要なメモを残すコメントでしたら、もうすこし具体的なコメントに、不要なコメントでしたら削除したほうが、1年後の自分が悩まずに済むかと思います！

2020-09-21 14:04 UTC, TsukasaKashima commented
ご確認ありがとうございます！

こちら率直に申し上げますと「消し忘れ」のようなものでして、コードの改修を重ねる中でのここが問題点っぽい的なメモ書きのような感じでした。

レビューいただき誠にありがとうございます！
以降に関しましてはこういったところもなるべく削除した上でのcommitを心掛けていきたいと思います！

2020-09-21 14:57 UTC, azusa-ttt commented
ありがとうございます！
背景については承知しましたが、修正は今後のプルリクエストで行われるでしょうか？

2020-09-22 04:55 UTC, TsukasaKashima commented
そうですね！
次のissueならびにプルリクで修正予定でした！

2020-09-22 04:57 UTC, azusa-ttt commented
なるほど！そういうことでしたら、approveしますね！

2020-09-22 04:57 UTC, azusa-ttt approved these changes

2020-09-22 04:58 UTC, merged